## General settings ##
## A single whitespace is needed after the colons where settings are adjusted##
General: ## Nothing goes here ##
  Server: ## Nothing goes here ##
    # Tips to the server will be sent to this address
    XRP_Wallet_Address:
    XUMM: ## Nothing goes here ##
      # ** REQUIRED ** - See the instructions on https://www.ezpzxrp.com/?p=350 to fill in these values.
      API_KEY:
      API_SECRET:
